### PR TITLE
SQL_DDL_Func_HW

### PR DESCRIPTION
**Pull request by gergelyzsolnai**
Hello Aleana,

I am very sorry for the delay. I had some stress issues.....I couldn't solve an issue in one task (task 4.), which i still can not, and i almost gave up. 
Volha helped me put myself together to continue. 
I know i am on a delay, i hope i can catch up with the others as well.

### CODE REVIEW

**Review by DrevinaAlena — CHANGES_REQUESTED** [review]
Hi @gergelyzsolnai ,
Please pay attention to my comments and recommendations:
-poor description,
-only 2 files are expected to be in the current branch,
-T1: no schema mentioned, UPPER/LOWER for conditions with string columns is missing;
-T2: no schema mentioned, ERROR: column "input_country" does not exist;
-T3: no schema mentioned,  UPPER/LOWER for conditions with string columns is missing, please pay attention on the provided example of the expected column naming (in capitalized way), why you 'DROP FUNCTION most_popular_films_by_countries(text[]);' if you recreate the fnction;
-T4: no schema mentioned, hint- 'the corresponding last rental data, if  available', here it's expected to be seen another type of logic, drop function? ;
-T5: no schema mentioned, drop function? ;
-T6: done, optional tasks are done as well

Kind Regards,
Alena.

**Comment by gergelyzsolnai** [comment]
@DrevinaAlena 
Hello Alena,

I am sorry about the poor description, but i had to explain why i was late on homework. I am very happy that i could move forward in many problems!

Finally i found the logic for the task 4 as well. 

I left drop functions because i forgot leaving them, when i was testing the codes. 
I learned to put always schema, i will never forget it, i promise. 

Best regards,
Gergely

**Comment by DrevinaAlena** [comment]
Hi @gergelyzsolnai,
still poor description,
but it could be merged.

Regards,
Alena.

**Review by DrevinaAlena — APPROVED** [review]

**Comment by DrevinaAlena** [comment]
Could you write any message in learn portal?

**Comment by gergelyzsolnai** [comment]
Sorry, now i understand what you meant description. I thought description is poor for the PR. 
It is not poor, because i did not write any, honestly i forgot. 
Can i write descriptions, and after merging the branch?

**Comment by DrevinaAlena** [comment]
Please, write, just indicate the logic you used for each task.

**Comment by gergelyzsolnai** [comment]
@DrevinaAlena 

I wrote the logics in descriptions. Sorry for misunderstanding.
Also found an error in task 3, which i corrected.

**Comment by DrevinaAlena** [comment]
good job!

**Pull request merged**
