### PR TITLE
SQL_DML_HW

### PR DESCRIPTION
**Pull request by gergelyzsolnai**
I am ready with the two homework tasks.

### CODE REVIEW

**Comment by gergelyzsolnai** [comment]
@DrevinaAlena 
Sorry Alena, i forgot, that i have to do my rental dynamic. It is okay in my database, but my inventory_id, and rental_id, payment_id is fixed. It will definitely not fit in your database. 
I have to rewrite my codes, to make them dynamic. 
Please, give me a day, i will modify my code until tomorrow morning. 
Thank you!
Gergely

**Comment by gergelyzsolnai** [comment]
@DrevinaAlena 
Hello Alena,
I am ready, thank you for your patience.
Gergely

**Review by DrevinaAlena — CHANGES_REQUESTED** [review]
Hi @gergelyzsolnai ,
good job!

Could you improve your work based on my comments:
Task1:
1) used hardcode:
in T1.5 Updating a customer to my datas: 87-id
in T1.6 Removing any records related to me (as a customer) from all tables except 'Customer' and 'Inventory'
2) Don't hardcode IDs. Instead of construction INSERT INTO … VALUES use INSERT INTO … SELECT …
3) All tasks are expected to be checked on duplicated by using WHERE NOT EXISTS, IF NOT EXISTS, ON CONFLICT DO NOTHING, etc.
4) Could you pay attention on the correctness naming of the PR title (name of the PR should be: SQL_DML_HW)

Task2: well-done

Kind Regards,
Alena.

**Comment by gergelyzsolnai** [comment]
@DrevinaAlena 

Hello Alena, 

Please check my changes. 
I watched QA session many times, when i could manage to do it without hardcoding any. 
I hope it will be good. 
Sorry about the naming of the PR, i don't know, what happened, i did not mean it by purpose. 

Best wishes, 
Gergely

**Comment by DrevinaAlena** [comment]
Hi @gergelyzsolnai 
good job!

Could be merged,
write any message in learn related to this module.

Regards,
Alena.

**Review by DrevinaAlena — APPROVED** [review]

**Pull request merged**
