### PR TITLE
DB_HW_Sushi

### PR DESCRIPTION
**Pull request by gergelyzsolnai**
File updated as you suggested.

### CODE REVIEW

**Review by DrevinaAlena — CHANGES_REQUESTED** [review]
Hi @gergelyzsolnai , 
good job,
file was done corrected.
But in your branch should be only one file with your task, the rest files must be deleted. 
image

Regards,
Alena.

**Review by DrevinaAlena — APPROVED** [review]
well-done! thank you.

**Comment by gergelyzsolnai** [comment]
I cleaned everything, except the homework file. Sorry, it was a mess. :(

**Comment by DrevinaAlena** [comment]
Hi @gergelyzsolnai ,

in order to resolve your conflict, in the current moment in your main branch must be only these files 
image
and then try again to merge your branch DB_HW_Sushi with your done task to main branch.

Regards,
Alena.

**Comment by gergelyzsolnai** [comment]
Thank you for the help! :)

**Pull request merged**
