### PR TITLE
SQL_SELECT_HW

### PR DESCRIPTION
**Pull request by gergelyzsolnai**

### CODE REVIEW

**Comment by gergelyzsolnai** [comment]
I sent pull request, because i thought i can not do PART 3's second option, but i think i know now how to do it. 
How can i edit file, or should i write my solution here?

**Comment by DrevinaAlena** [comment]
Hi @gergelyzsolnai ,
you can update your file in this branch.
When you are ready with the update, just tag me here.

Regards,
Alena.

**Comment by gergelyzsolnai** [comment]
Ready. @DrevinaAlena I got the inner self join idea from the SQL simulators. Thank god i started working on pgexercises.com. 
I hope you find it good.

**Review by DrevinaAlena — CHANGES_REQUESTED** [review]
Hi @gergelyzsolnai 
very good job!
Please pay attention to my comments and recommendation.

**_Result:_**
Submit the result as an sql. file and place it in your git repository: SQL_SELECT_Name_Surname_HW.sql     **done**
name of the PR should be: SQL_SELECT_HW     **done**
name of the Branch should be: SQL_SELECT_HW     **done**
In the 'Answer' section below in Learn, please provide your repository link     **done**
**!!! In the branch you created, only the files requested by the task should be present. Please revise your approach by adding only new files. At this moment, please adjust the number of files to the expected quantity. In the future, upload only the new files.**

**_Note:_**
Please add comments why you chose a particular way to solve each tasks.    **done**
IDs should not be hardcoded   -**done**
Don't use column number in GROUP BY and ORDER BY   - **done**
Specify JOIN types (INNER/RIGHT/LEFT/CROSS) - **done**
Use code formatting standards    - **undone**
You cannot use window functions     -**used in task3.v2**
We request you test your work before commit it. Code should run w/o errors     -**done**


**_What should be done_**

Part 1: Write SQL queries to retrieve the following data

1) All animation movies released between 2017 and 2019 with rate more than 1, alphabetical

Minor issue: 
-no formatting according to standards;
-missing UPPER/LOWER in filters; 
-don't forget indicate the alias of a table before indicating the column (ORDER BY f.title ASC;)

2) The revenue earned by each rental store since March 2017 (columns: address and address2 – as one column, revenue)
Minor issue: 
-no formatting according to standards;
Serious error:
-FROM clause includes the incorrect tables, that's why the values of the column revenue are incorrect;


3) Top-5 actors by number of movies (released since 2015) they took part in (columns: first_name, last_name, number_of_movies, sorted by number_of_movies in descending order)
Minor issue: 
-no formatting according to standards;
-in group by it's expected to work with a.actor_id  to find film's amount per actor


4) Number of Drama, Travel, Documentary per year (columns: release_year, number_of_drama_movies, number_of_travel_movies, number_of_documentary_movies), sorted by release year in descending order. Dealing with NULL values is encouraged)
Minor issue:
-no formatting according to standards;
-JOIN types incorrect using , in the current task better use inner join.


5)For each client, display a list of horrors that he had ever rented (in one column, separated by commas), and the amount of money that he paid for it
Minor issue:
-no formatting according to standards;
-using alias instead of column name in GROUP BY (GROUP BY client_name;) as GROUP BY clause references column names directly from the database.



Part 2: Solve the following problems using SQL

1. Which three employees generated the most revenue in 2017? They should be awarded a bonus for their outstanding performance. 

Assumptions: 
staff could work in several stores in a year, please indicate which store the staff worked in (the last one);
if staff processed the payment then he works in the same store; 
take into account only payment_date
Minor issue:
-no formatting according to standards;
-using alias instead of column name in GROUP BY.


2. Which 5 movies were rented more than others (number of rentals), and what's the expected age of the audience for these movies? To determine expected age please use 'Motion Picture Association film rating system
Minor issue:
-no formatting according to standards.


Part 3. Which actors/actresses didn't act for a longer period of time than the others? 
The task can be interpreted in various ways, and here are a few options:

V1: gap between the latest release_year and current year per each actor;
Minor issue:
-no formatting according to standards;
-using alias instead of column name in GROUP BY.

V2: gaps between sequential films per each actor;
Minor issue:
-no formatting according to standards;
-window functions shouldn't be used, pls redo this task without using it.

What should be corrected:
1) for all tasks 'Use code formatting standards';
(
like this:
SELECT 
   f.title
FROM 
   category c 
   INNER JOIN film_category fc  ON fc.category_id = c.category_id 
   INNER JOIN film f            ON f.film_id = fc.film_id 
WHERE 
 UPPER(c.name) = 'ANIMATION'            
 AND  f.release_year BETWEEN 2017 AND 2019
 and  f.rental_rate >=1
ORDER BY 
   f.title asc;
)
2)redo tasks using column name in GROUP BY instead of alias 
...
and all other issues indicated in comments.

Kind Regards,
Alena.

**Comment by gergelyzsolnai** [comment]
@DrevinaAlena 
Oh my god, how many mistakes, thank you for your suggestions!
I am sorry about the formatting and about the extra several files. 

I did not know that PARTITION BY is windows function, i did not know how to solve it, and i searched in google. I did not check is it windows function. Thank you for letting me know. I am very very sorry about that. 
I need to think how to solve the task. 
I can start working on the sql file on wednesday.

**Comment by gergelyzsolnai** [comment]
@DrevinaAlena 
I am ready, but i don't think my PART 1 /2 is good.

**Comment by DrevinaAlena** [comment]
Hi @gergelyzsolnai 

1) formatting is still not good, I provided example but it seams to me it illustrated incorrect intervals, so here is the picture:
image
2) T1.2 is incorrect, pls use this list of tables for joining:
payment
rental
inventory
store
address
3) V2 the solution is too complicated, and the result should be 
image
Pls correct your code.

Regards,
Alena.

**Comment by gergelyzsolnai** [comment]
@DrevinaAlena 
Maybe i have problem to understand the task. I searched for Cameron Wray, and his movies. He started acting in 1990 and last movie was in 2019. He was busy acting in 14 yrs, and was not active about 15 yrs. On your image he had 12 inactive years.
So it is not that i thought. I thought i have to summarize the inactive years, but not. 
Please, explain to me, what is the task exactly?

**Comment by DrevinaAlena** [comment]
Hi @gergelyzsolnai 
I try to rephrase Task3:
V2 : Find out who had the longest break between two movies.

P.S. Just indicate name and surname of the actor.

**Comment by gergelyzsolnai** [comment]
@DrevinaAlena 
Thank you for your suggestions. I formatted the file, it is more clear now, sorry about that.

I updated the task 3 v2 code, but it's result is absolutely different than yours, but i believe it has to be good! :)
I am sorry, but i can't move forward, but i have to start working on the TCL and DML-s, because i will ran out of time. 
If my solution is not good, please let it go. I give up :(

**Review by DrevinaAlena — APPROVED** [review]

**Comment by DrevinaAlena** [comment]
Hi @gergelyzsolnai ,
good job!
approved for merge)
Could you write any message in learn portal for this module?

Best wishes, 
Alena

**Comment by gergelyzsolnai** [comment]
Thank you!

**Pull request merged**
