### PR TITLE
DB_HW_Political_Campaign

### PR DESCRIPTION
**Pull request by gergelyzsolnai**
Hi! 

I am ready with the political campaign DB homework.

### CODE REVIEW

**Review by DrevinaAlena — CHANGES_REQUESTED** [review]
Hi @gergelyzsolnai ,

1) The description of your created database should be provided using **the template provided by EPAM.**
and 
Parts: 2.2 LOGICAL SCHEME and 2.3 OBJECTS must be separated, and tables should be used for the table description and its data.

2) Incorrect file name uploaded. For a graphical image, the filename should be: DB_Name_Surname_HW_YourTopic_diagram.png

3) Could you use a **white background** in your diagram? I can't discern the relationships between tables.

4) Add me each time as a reviewer when you create PR.

Regards, 
Alena

**Comment by gergelyzsolnai** [comment]
I have done the changes, but conflict is still there.

**Comment by DrevinaAlena** [comment]
Hi @gergelyzsolnai ,
In any case, the conflict with the branch should be resolved; pay attention to the step-by-step suggestion from GitHub's side:
image

Regards,
Alena

**Comment by DrevinaAlena** [comment]
1)The template, along with its description, should be downloaded and then edited (please click on 'Enable Editing'). Please redo it and include an example with data.

2) Could you just rename your file name, related to the diagram, should be DB_Gergely_Zsolnai_HW_Political_Campaign_diagram.png, the diagram was done good.

**Comment by gergelyzsolnai** [comment]
I hope i am ready :)

**Comment by DrevinaAlena** [comment]
Hi @gergelyzsolnai ,
1) this file must be deleted from this branch, please, be attentive to what you upload to the specific branch
image
2) DB_Gergely_Zsolnai_HW_Political_Campaign_diagram.png - done
3) DB_Gergely_Zsolnai_HW_Political_campaign_descriptions.docs - done partially (there are not examples with data for each table), next time pay attention to design of your work (different font, text size, each word was capitalized in the bullet list!?)

After completing point 1 , the work can be merged.
Regards, 
Alena

**Review by DrevinaAlena — APPROVED** [review]

**Pull request merged**
